export default{
    EN: {
        LABEL_TITLE:"HOME",
        LABEL_WELCOME:"Welcome Back",
        LABEL_OPSNEWS:"Operation News",
        LABEL_EVENT:"Event News",
        LABEL_BANNER:"Banner News",
        LABEL_OPSLIST:"Operator List",
        LABEL_TASKLIST:"Task List",
        LABEL_SUB_OPSNEWS:"External Link about operation",
        LABEL_SUB_EVENT:"External Link about event",
        LABEL_SUB_BANNER:"External Link about gatcha",
        LABEL_SUB_OPSLIST:"Internal feature about operator list",
        LABEL_SUB_TASKLIST:"Internal feature about task",
    },
    ID: {
        LABEL_TITLE:"HOME",
        LABEL_WELCOME: "Selamat Datang Kembali",
        LABEL_OPSNEWS: "Berita Operasi",
        LABEL_EVENT: "Berita Acara",
        LABEL_BANNER: "Banner News",
        LABEL_OPSLIST: "Daftar Operator",
        LABEL_TASKLIST: "Daftar Tugas",
        LABEL_SUB_OPSNEWS: "Tautan Eksternal tentang operasi",
        LABEL_SUB_EVENT: "Tautan Eksternal tentang acara",
        LABEL_SUB_BANNER: "Tautan Eksternal tentang gatcha",
        LABEL_SUB_OPSLIST: "Fitur internal tentang daftar operator",
        LABEL_SUB_TASKLIST: "Fitur internal tentang tugas",
    },
}